name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

  # deploy:
  #   name: Deploy to Production
  #   runs-on: ubuntu-latest
  #   needs: [lint]
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4
  #     -
  #       name: Deploy to Production Server
  #       run: |
  #         echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
  #         chmod 600 private_key
  #         ssh -i private_key -o StrictHostKeyChecking=no root@147.79.100.153 'cd /root/projects/test-frankenphp && git pull origin main && composer install && make cc'
  #       env:
  #         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: 147.79.100.153
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/test-frankenphp
            git pull origin main
            composer install
            make cc